GOOGLE_SEARCH_API       = 'AIzaSyDRz_NSI8xinqGLyuD5_bfWYHl0AXvtCfI'
GOOGLE_SEARCH_ENGINE_ID = '56e08389160f847c2'
GOOGLE_SEARCH_LIMIT     = 10

PAST_QUERY_FILE         = 'past_query_file.txt'

MODEL_RESPONSE_LIMIT    = 10